import { useState } from 'react';
import { Plus, X } from 'lucide-react';

const faqs = [
  {
    question: 'What types of content can I upload?',
    answer: 'Tavazi welcomes feature films, documentaries, short films, series, and pay-per-view events. We focus on authentic African storytelling -- content that reflects African experiences, cultures, and perspectives. All content goes through a quality review process before being published on the platform.',
  },
  {
    question: 'How and when do I get paid?',
    answer: 'Creators receive 60-70% of every sale generated by their content. Payments are processed monthly through M-Pesa, Paystack, and other local payment methods supporting KES, NGN, GHS, ZAR, and USD. You can track your earnings in real-time through the creator dashboard.',
  },
  {
    question: 'Do I have to give exclusive rights?',
    answer: 'No. Tavazi operates on a non-exclusive licensing model. You retain full ownership of your content and are free to distribute it on other platforms simultaneously. We believe creators should have complete control over where and how their work is shared.',
  },
  {
    question: 'What quality requirements are there?',
    answer: 'We require a minimum of HD (1080p) resolution for all uploads. Our adaptive streaming technology automatically optimises playback for each viewer\'s connection speed, ensuring professional-quality viewing experiences across Africa and globally.',
  },
  {
    question: 'How do I price my content?',
    answer: 'You set your own prices. Choose from subscription-based access, pay-per-view, or ad-supported models -- or combine them. Our team can help you develop pricing strategies based on your audience and content type to maximise your revenue.',
  },
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section className="py-24 px-6 bg-tavazi-dark">
      <div className="max-w-3xl mx-auto">
        <h2 className="font-display text-3xl md:text-4xl text-cream text-center mb-16">
          Frequently Asked <span className="text-tavazi-navy">Questions</span>
        </h2>

        <div className="space-y-3">
          {faqs.map((faq, i) => {
            const isOpen = openIndex === i;
            return (
              <div key={i} className="border border-tavazi-navy/15 rounded-lg overflow-hidden">
                <button
                  onClick={() => setOpenIndex(isOpen ? null : i)}
                  className="w-full flex items-center justify-between px-6 py-5 text-left transition-colors duration-200 hover:text-tavazi-navy group"
                >
                  <span className="font-display text-lg text-cream group-hover:text-tavazi-navy transition-colors">
                    {faq.question}
                  </span>
                  <span className="shrink-0 ml-4 transition-transform duration-300">
                    {isOpen ? (
                      <X className="w-5 h-5 text-tavazi-navy" />
                    ) : (
                      <Plus className="w-5 h-5 text-cream/40" />
                    )}
                  </span>
                </button>
                <div
                  className="overflow-hidden transition-all duration-300"
                  style={{ maxHeight: isOpen ? '300px' : '0px' }}
                >
                  <p className="px-6 pb-5 text-cream/60 text-sm leading-relaxed">
                    {faq.answer}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
